### ISSUE TITLE
Cannot launch loader

### ISSUE THREAD

**Issue by e-lisa** [clague/ds3os-loader-rs#1]
Launching the loader brings up a blank window, seems to be an issue with fontconfig versions. See attached for log.

Let me know if you need any additional debugging information.

Thanks for the project, keep up the great work!

Using Pop!_OS 21.10

$ lsb_release -a
No LSB modules are available.
Distributor ID: Pop
Description:    Pop!_OS 21.10
Release:        21.10
Codename:       impish

See attached for log:

[ds3os.log](https://github.com/clague/ds3os-loader-rs/files/8337820/ds3os.log)

**Comment by e-lisa** [comment]
Wanted to add:

Using the "Build" tag to build. Had to install the following dependencies to build:

cargo libexpat-dev libfreetype-dev libssl-dev

**Comment by clague** [comment]
> Okay, something different fixed the problem, and I think it's worth putting that whole `fontconfig` stuff right into the `README.md`.
>
>- So, (Linux) users should definitely check whether or not `fontconfig` is out of date. It wasn't in my case.
>- At least Ubuntu users should also ensure that the package `libfontconfig1-dev` is installed. I have no damn idea *what* `iced` otherwise links to, but once this package is installed via `apt install libfontconfig1-dev`, the `iced` applications boot up instantly.
>
>_Originally posted by @Evrey in https://github.com/iced-rs/iced/issues/199#issuecomment-589686734_

So `libfontconfig1-dev` seems to be needed for debian-based distro.

**Comment by NullDev** [comment]
@clague I just wanted to hijack this issue to say: Thank you so so much for this project. It works like a charm! Was really frustrating not being able to play with my friends. Never got ds3os loader to work with proton/wine. Then I cloned this project, built it, and it instantly worked! So again: Thank you! :heart:
