### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by Bratjuuc** [clague/ds3os-loader-rs#3]
When compiling some of the late libraries fail to compile.

```error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 2]`
  --> /home/artyom/.cargo/registry/src/github.com-1ecc6299db9ec823/native-dialog-0.6.3/src/dialog_impl/gnu/message.rs:62:18
   |
62 |         .replace(&[' ', '\t'], "&nbsp;")
   |          ------- ^^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 2]`
   |          |
   |          required by a bound introduced by this call
   |
   = help: the trait `Fn<(char,)>` is not implemented for `[char; 2]`
   = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 2]`
   = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 2]`

**Comment by clague** [comment]
close as resolved in discord

> Need the nightly rust.
